discussion/discussion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todolist/', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

discussion/todolist/urls.py
from django.urls import path, re_path
from . import views


# Syntax
# path(route, view, name)

app_name ='todolist'

urlpatterns = [
	path('', views.index, name='index'),
	#/todolist/<todoitem_id>
	#/todolist/1
	# /todolist/register
	path('register', views.register, name='register'),
	path('change_password', views.change_password, name="change_password"),
	path('login', views.login_view, name="login"),
	path('logout', views.logout_view, name="logout"),
	path('add_task', views.add_task, name="add_task"),
	path('add_event', views.add_event, name="add_event"),
    # The <int:todoitem_id> allows for creating a dynamic link where the todoitem_id is provided
	# path('<int:eventitem_id>/', views.eventitem, name='vieweventitem'),
	# path('<int:todoitem_id>/', views.todoitem, name='viewtodoitem'),
	re_path(r'^eventitem/(?P<eventitem_id>\d+)/$', views.eventitem, name='vieweventitem'),
    re_path(r'^todoitem/(?P<todoitem_id>\d+)/$', views.todoitem, name='viewtodoitem'),
	path('<int:todoitem_id>/edit', views.update_task, name='update_task'),
	path('<int:todoitem_id>/delete', views.delete_task, name='delete_task'),
	
]

discussion/todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ToDoItem(models.Model):
	task_name = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="pending")
	date_created = models.DateTimeField('date created')
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

class EventItem(models.Model):
	event_name = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default='pending')
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

discussion/todolist/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=20)
    password = forms.CharField(label='Password', max_length=20)

class RegisterForm(forms.Form):
    username = forms.CharField(label='Username', max_length=20)
    first_name = forms.CharField(label='First Name', max_length=20)
    last_name = forms.CharField(label='Last Name', max_length=20)
    email = forms.CharField(label='Email', max_length=20)
    password = forms.CharField(label='Password', max_length=20)
    confirm_password = forms.CharField(label='Confirm Password', max_length=20)

class UpdateProfileForm(forms.Form):
    first_name = forms.CharField(label='first_name', max_length=20)
    last_name = forms.CharField(label='last_name', max_length=20)
    password = forms.CharField(label='Password', max_length=20)


class AddTaskForm(forms.Form):
    task_name = forms.CharField(label='Task Name', max_length=50)
    description = forms.CharField(label='Description', max_length=200)


class UpdateTaskForm(forms.Form):
    # If fields are optional, using the "Model.save()" method will not work
    # Using the option "required=False" will allow the field to be optinal when updating a record
    # task_name = forms.CharField(label='Task Name', max_length=50, required=False)
    task_name = forms.CharField(label='Task Name', max_length=50)
    description = forms.CharField(label='Description', max_length=200)
    status = forms.CharField(label='Status', max_length=50)


class AddEventForm(forms.Form):
    event_name = forms.CharField(label='Event Name', max_length=50)
    description = forms.CharField(label='Description', max_length=200)
    

discussion/todolist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
# from django.template import loader
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.forms.models import model_to_dict
from django.utils import timezone

from .models import ToDoItem, EventItem

# Local Imports
from .models import ToDoItem
from .forms import LoginForm, AddTaskForm, UpdateTaskForm, RegisterForm, AddEventForm, UpdateProfileForm


def index(request):
	
	todoitem_list = ToDoItem.objects.filter(user_id=request.user.id)
	eventitem_list = EventItem.objects.filter(user_id=request.user.id)
	context = {
		'todoitem_list': todoitem_list,
		'eventitem_list': eventitem_list,
		'user': request.user
		}

	return render(request, "todolist/index.html", context)


def todoitem(request, todoitem_id):
	
	# todoitem = model_to_dict(ToDoItem.objects.get(pk=todoitem_id))
	todoitem = get_object_or_404(ToDoItem, pk=todoitem_id)

	return render(request, "todolist/todoitem.html", model_to_dict(todoitem))

def register(request):
	context = {}

	if request.method == 'POST':
		form = RegisterForm(request.POST)
		if form.is_valid() == False:
			form = RegisterForm()
		else:
			username = form.cleaned_data['username']
			first_name = form.cleaned_data['first_name']
			last_name = form.cleaned_data['last_name']
			email = form.cleaned_data['email']
			password = form.cleaned_data['password']
			confirm_password = form.cleaned_data['confirm_password']

			duplicate = User.objects.filter(username=username)

			if duplicate:
				context = {
					"error": True,
					"message": "username already exists"
				}
			elif password != confirm_password:
				context = {
					"error": True,
					"message": "password not matching"
				}
			else:
				user = User()
				user.username = username
				user.first_name = first_name
				user.last_name = last_name
				user.email = email
				user.set_password(password)
				user.is_staff = False
				user.is_active = True
				user.save()
				
				user = authenticate(username=username, password=password)
				login(request, user)
				return redirect('todolist:index')

	return render(request, "todolist/register.html", context)


def change_password(request):
	user = request.user
	context = {
		'first_name': user.first_name,
		'last_name': user.last_name
	}

	if request.method == 'POST':
		form = UpdateProfileForm(request.POST)
		if form.is_valid() == False:
			form = UpdateProfileForm()
		else:
			first_name = form.cleaned_data['first_name']
			last_name = form.cleaned_data['last_name']
			password = form.cleaned_data['password']
			user.set_password(password)
			user.first_name = first_name
			user.last_name = last_name
			user.save()
			context = {
				'success': True,
				'message': 'Successfully Updated Profile'
			}

	return render(request, "todolist/change_password.html", context)

def login_view(request):
	context = {}

	# If this is a POST request we need to process the form data
	if request.method == 'POST':
		# Create a form instance and populate it with data from the request
		form = LoginForm(request.POST)

		# Check whether the data is valid
		# Runs validation routines for all the form fields and returns True and places the form's data in the "cleaned_data" attribute
		if form.is_valid() == False:
			# Returns a blank login form
			form = LoginForm()
		else:
			# Retrieves the information from the form
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user = authenticate(username=username, password=password)
			context = {
				"username": username,
				"password": password
			}

			if user is not None:
				#Saves the user's ID in the session using Django's session framework
				login(request, user)
				return redirect('todolist:index')
			else:
				# Provides context with error to conditionally render the error message
				context = {
					"error": True
				}
	
	return render(request, "todolist/login.html", context)


def logout_view(request):
	logout(request)
	return redirect("todolist:index")



def add_task(request):
	context = {}

	if request.method == 'POST':
		form = AddTaskForm(request.POST)
		if form.is_valid() == False:
			form = AddTaskForm()
		else:
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']

			# Checks the database if a task already exists
			# By default the "filter" method searches for records that are case insensitive
			duplicates = ToDoItem.objects.filter(task_name=task_name)

			# if todoitem does not contain any duplicates
			if not duplicates:
				# Creates an object based on the "TodoItem" model and saves the record in the database
				ToDoItem.objects.create(task_name=task_name, description=description, date_created=timezone.now(), user_id=request.user.id)
				return redirect('todolist:index')
			
			else:
				context = {
					"error": True
				}
	return render(request, "todolist/add_task.html", context)


def update_task(request, todoitem_id):
	# Returns a queryset
	todoitem = ToDoItem.objects.filter(pk=todoitem_id)

	# Accessing the first element is necessary because the 
	# "ToDoItem.objects.filter()" method returns a queryset
	context = {
		"user": request.user,
		"todoitem_id": todoitem_id,
		"task_name": todoitem[0].task_name,
		"description": todoitem[0].description,
		"status": todoitem[0].status,
	}

	if request.method == 'POST':
		form = UpdateTaskForm(request.POST)
		if form.is_valid() == False:
			form = UpdateTaskForm()
		else:
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']
			status = form.cleaned_data['status']

			if todoitem:
				todoitem[0].task_name = task_name
				todoitem[0].description = description
				todoitem[0].status = status

				todoitem[0].save()
				return redirect('todolist:index')
			else:
				context = {
					"error": True
				}
	return render(request, "todolist/update_task.html", context)

def delete_task(request, todoitem_id):
	todoitem = ToDoItem.objects.filter(pk=todoitem_id).delete()
	return redirect('todolist:index')



def add_event(request):
	context = {}

	if request.method == 'POST':
		form = AddEventForm(request.POST)
		if form.is_valid() == False:
			print('here error')
			form = AddEventForm()
		else:
			event_name = form.cleaned_data['event_name']
			description = form.cleaned_data['description']

			duplicate = EventItem.objects.filter(event_name=event_name)

			if not duplicate:
				EventItem.objects.create(event_name=event_name, description=description, user_id=request.user.id)
				return redirect('todolist:index')
			else:
				context = {
					"error": True,
					"message": 'event already created'
				}

	return render(request, "todolist/add_event.html", context)


def eventitem(request, eventitem_id):
	eventitem = get_object_or_404(EventItem, pk=eventitem_id)
	return render(request, "todolist/eventitem.html", model_to_dict(eventitem))

discussion/todolist/templates/todolist/add_event.html
{% extends 'base.html' %}
{% block title %}Add Event{% endblock %}

{% block content%}
    <div class="container">
        <div class="row">
            <div class="col-6 offset-3">
                <h1 class="text-center my-3">Add A Event</h1>
                {% if error == True %}
                    <p class="text-danger">{{ message }}</p>
                {% endif %}
                <form action="{% url 'todolist:add_event' %}" method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="event_name">Event Name: </label>
                        <input type="text" class="form-control" name="event_name"  maxlength="50" required>
                    </div>
                
                    <div class="mb-3">
                        <label for="description">Description: </label>
                        <textarea class="form-control" name="description"  required></textarea>
                    </div>
                
                    <div class="text-center">
                        <input type="submit" value="Add Event" class="btn btn-success">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

discussion/todolist/templates/todolist/add_task.html
{% extends 'base.html' %}
{% block title %}Add Task{% endblock %}

{% block content%}
    <div class="container">
        <div class="row">
            <div class="col-6 offset-3">
                <h1 class="text-center my-3">Add A Task</h1>
                {% if error == True %}
                    <p class="text-danger">Duplicate Task Found</p>
                {% endif %}
                <form action="{% url 'todolist:add_task' %}" method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="task_name">Task Name: </label>
                        <input type="text" class="form-control" name="task_name"  maxlength="50" required>
                    </div>
                
                    <div class="mb-3">
                        <label for="description">Description: </label>
                        <textarea class="form-control" name="description"  required></textarea>
                    </div>
                
                    <div class="text-center">
                        <input type="submit" value="Add Task" class="btn btn-success">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

discussion/todolist/templates/todolist/change_password.html
{% extends 'base.html' %}

{% block title %}Update Profile{% endblock %}
{% block content %}

{% if user.is_anonymous == False %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Update Profile</h1>
				{% if success == True %}
					<p class="text-success">{{ message }}</p>
				{% endif %}
				<form action="{% url 'todolist:change_password' %}" method="post">
					{% csrf_token %}
					<div class="mb-3">
						<label for="first_name">First Name</label>
						<input type="text" class="form-control" id="first_name" name="first_name" value="{{first_name}}" maxlength="20" required>                    
					</div>

					<div class="mb-3">
						<label for="last_name">Last Name</label>
						<input type="text" class="form-control" id="last_name" name="last_name" value="{{last_name}}" maxlength="20" required>                    
					</div>

					<div class="mb-3">
						<label for="password">Password</label>
						<input type="password" class="form-control" id="password" name="password" value="" maxlength="20" required>                    
					</div>

					<div class="text-center">
						<input type="submit" class="btn btn-success" value="Update">
					</div>
				</form>
			</div>
		</div>
	</div>

{% elif user.is_anonymous == True %}
	<h1 class="text-center my-3">You are not authorized to access this page.</h1>
	<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
{% endif %}
{% endblock %}

discussion/todolist/templates/todolist/eventitem.html
{% extends 'base.html' %}

{% block title %}Event Item{% endblock %}

{% block content %}

    <div class="text-center my-3">
        <h1>{{event_name}}</h1>
        <h3>Description</h3>
        <p>{{description}}</p>
        <h3>Status</h3>
        <p>{{status}}</p>
        
        <button class="btn btn-warning mx-1 text-decoration-none">
            <a href="{% url 'todolist:index' %}" class="text-light text-decoration-none">Back To Home</a>
        </button>
    </div>

{% endblock %}

discussion/todolist/templates/todolist/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
	{% if user.is_anonymous == False %}
		<h1 class="text-center my-3">Welcome, {{user.first_name}} {{user.last_name}}</h1>

		{% if todoitem_list %}
			<div class="container">
				<div class="row">
					<h3 class="text-center mb-3">My Tasks</h3>
					<ul class="list-group col-lg-2 offset-lg-5 text-center">
						{% for todoitem in todoitem_list %}
							<li class="list-group-item">
								<a class="text-decoration-none" href="{% url 'todolist:viewtodoitem' todoitem.id %}">{{todoitem.task_name}}</a>
							</li>
						{% endfor %}
					</ul>
				</div>
			</div>
		{% else %}
			<p>No Task Have been created yet</p>
		{% endif %}

		{% comment %} here {% endcomment %}
		{% if eventitem_list %}
			<div class="container">
				<div class="row">
					<h3 class="text-center mb-3">My Events</h3>
					<ul class="list-group col-lg-2 offset-lg-5 text-center">
						{% for eventitem in eventitem_list %}
							<li class="list-group-item">
								<a class="text-decoration-none" href="{% url 'todolist:vieweventitem' eventitem.id %}">{{eventitem.event_name}}</a>
							</li>
						{% endfor %}
					</ul>
				</div>
			</div>
		{% else %}
			<p>No Events Have been created yet</p>
		{% endif %}


	{% elif user.is_anonymous == True %}
		<h1 class="text-center my-3">You are not authorized to access this page.</h1>
		<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
	{% endif %}

{% endblock %}

discussion/todolist/templates/todolist/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            <h1 class="text-center my-3">Login</h1>
            {% if error == True %}
                <p class="text-danger">Invalid user credentials, please check your username and password</p>
            {% endif %}
            <form action="{% url 'todolist:login' %}" method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" id="username" name="username" value="{{username}}" maxlength="20" required>                    
                </div>

                <div class="mb-3">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name="password" value="{{password}}" maxlength="20" required>                    
                </div>

                <div class="text-center">
                    <input type="submit" class="btn btn-success" value="Login">
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

{% comment %} {% if is_user_authenticated == False %}
	<h1>Something went Wrong</h1>
	<p>Please contact your administrator or reset your password</p>
	<a href="{% url 'todolist:index' %}"> Back to the index page</a>
{% endif %} {% endcomment %}

discussion/todolist/templates/todolist/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            <h1 class="text-center my-3">Register</h1>
            <form action="{% url 'todolist:register' %}" method="post">
                {% csrf_token %}

                <div class="mb-3">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" id="username" name="username" maxlength="20" required>                    
                </div>

                <div class="mb-3">
                    <label for="first_name">First Name</label>
                    <input type="text" class="form-control" id="first_name" name="first_name" maxlength="20" required>                    
                </div>

                <div class="mb-3">
                    <label for="last_name">Last Name</label>
                    <input type="text" class="form-control" id="last_name" name="last_name" maxlength="20" required>                    
                </div>

                <div class="mb-3">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" id="email" name="email" maxlength="20" required>                    
                </div>

                <div class="mb-3">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name="password" maxlength="20" required>                    
                </div>

                <div class="mb-3">
                    <label for="confirm_password">Confirm Password</label>
                    <input type="password" class="form-control" id="confirm_password" name="confirm_password" maxlength="20" required>                    
                </div>

                <div class="text-center">
                    <input type="submit" class="btn btn-success" value="Register">
                </div>
				{% if error == True %}
               		<p class="text-danger">{{ message }}</p>
            	{% endif %} 
            </form>
        </div>
    </div>
</div>

{% endblock %}

discussion/todolist/templates/todolist/todoitem.html
{% extends 'base.html' %}

{% block title %}Todo Item{% endblock %}

{% block content %}

    <div class="text-center my-3">
        <h1>{{task_name}}</h1>
        <h3>Description</h3>
        <p>{{description}}</p>
        <h3>Status</h3>
        <p>{{status}}</p>
        
        <button class="btn btn-primary mx-1 text-decoration-none">
            <a href="{% url 'todolist:update_task' id %}" class="text-light text-decoration-none">Edit Task</a>
        </button>

        <button class="btn btn-danger mx-1 text-decoration-none">
            <a href="{% url 'todolist:delete_task' id %}" class="text-light text-decoration-none">Delete Task</a>
        </button>

        <button class="btn btn-warning mx-1 text-decoration-none">
            <a href="{% url 'todolist:index' %}" class="text-light text-decoration-none">Back To Tasks</a>
        </button>
    </div>

{% endblock %}

discussion/todolist/templates/todolist/update_task.html
{% extends 'base.html' %}
{% block title %}Update Task{% endblock%}

{% block content %}
    {% if user.is_anonymous == False %}
        <div class="container">
            <div class="row">
                <div class="col-6 offset-3">
                    <h1 class="text-center my-3">Update Task</h1>
                    {% if error == True %}
                        <p class="text-danger">Task not found</p>
                    {% endif %}
                    <form action="{% url 'todolist:update_task' todoitem_id %}" method="post">
                        {% csrf_token %}
                    
                        <div class="mb-3">
                            <label for="task_name">Task Name: </label>
                            <input type="text" class="form-control" id="task_name" name="task_name" value="{{ task_name }}" maxlength="50" required>
                        </div>
                    
                        <div class="mb-3">
                            <label for="description">Description</label>
                            <textarea name="description" id="description" class="form-control" required>{{description}}</textarea>
                        </div>
                    
                        <div class="mb-3">
                            <label for="Status">Status: </label>
                            <input type="text" class="form-control" id="status" name="status" value="{{ status }}" maxlength="50" required>
                        </div>
                    
                        <div class="text-center">
                            <input type="submit" class="btn btn-success" value="Update Task">
                        </div>
                    
                    </form>
                </div>
            </div>
        </div>
    {% else %}
        <h1 class="text-center my-3">You are not authorized to access this page.</h1>
        <p class="text-center">Kindly login <a href="{% url 'todolist:login'%}">here</a></p>
    {% endif %}
{% endblock %}