discussion/discussion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todolist/', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

discussion/todolist/urls.py
from django.urls import path, re_path
from . import views


# Syntax
# path(route, view, name)

app_name ='todolist'

urlpatterns = [
	path('', views.index, name='index'),
	#/todolist/<todoitem_id>
	#/todolist/1
	# /todolist/register
	path('register', views.register, name='register'),
	path('change_password', views.change_password, name="change_password"),
	path('login', views.login_view, name="login"),
	path('logout', views.logout_view, name="logout"),
	path('add_task', views.add_task, name="add_task"),
	path('add_event', views.add_event, name="add_event"),
    # The <int:todoitem_id> allows for creating a dynamic link where the todoitem_id is provided
	# path('<int:eventitem_id>/', views.eventitem, name='vieweventitem'),
	# path('<int:todoitem_id>/', views.todoitem, name='viewtodoitem'),
	re_path(r'^eventitem/(?P<eventitem_id>\d+)/$', views.eventitem, name='vieweventitem'),
    re_path(r'^todoitem/(?P<todoitem_id>\d+)/$', views.todoitem, name='viewtodoitem'),
	path('<int:todoitem_id>/edit', views.update_task, name='update_task'),
	path('<int:todoitem_id>/delete', views.delete_task, name='delete_task'),
	
]

discussion/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}To Do App{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  </head>
  <body>
    {% include "navbar.html" %}
    {% block content %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

discussion/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'todolist:index' %}">To Do App</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todolist:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todolist:add_task' %}">Add Task</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todolist:add_event' %}">Add Event</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todolist:change_password' %}">Update Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todolist:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todolist:login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todolist:logout' %}">Logout</a>
          </li>
        </ul>

      </div>
    </div>
  </nav>